/*
 * Copyright (c) 1998, 2001, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package mono.debugger.request;

import mono.debugger.ThreadMirror;
import mono.debugger.TypeMirror;

/**
 * Request for notification when a step occurs in the target VM.
 * When an enabled StepRequest is satisfied, an
 * {@link mono.debugger.event.EventSet event set} containing a
 * {@link mono.debugger.event.StepEvent StepEvent} will be placed on the
 * {@link mono.debugger.event.EventQueue EventQueue}.
 * The collection of existing StepRequests is
 * managed by the {@link EventRequestManager}
 *
 * @see mono.debugger.event.StepEvent
 * @see mono.debugger.event.EventQueue
 * @see EventRequestManager
 *
 * @author Robert Field
 * @since  1.3
 */
public interface StepRequest extends EventRequest
{
	public static enum StepDepth
	{
		Into,
		Over,
		Out
	}

	public enum StepSize
	{
		Min,
		Line
	}

	/**
	 * @return the thread on which the step event is being requested.
	 */
	ThreadMirror thread();

	/**
	 * @return the step size
	 */
	StepSize size();

	/**
	 * @return the step depth
	 */
	StepDepth depth();

	/**
	 * Restricts the events generated by this request to those whose
	 * location is in the given reference type or any of its subtypes.
	 * An event will be generated for any location in a reference type
	 * that can be safely cast to the given reference type.
	 *
	 * @param refType the reference type to filter on.
	 * @throws InvalidRequestStateException if this request is currently
	 *                                      enabled or has been deleted.
	 *                                      Filters may be added only to disabled requests.
	 */
	void addClassFilter(TypeMirror refType);
}
